Repository fetis/30-seconds-of-angular, pull requests merged in 2019-06, with the labels that each got.

#131 Adds twitter button in header
  .nvmrc
  builder/layouts/snippet.hbs
  builder/partials/footer.hbs
  builder/partials/head.hbs
  builder/partials/header.hbs
  builder/public/css/style.css
  builder/serve.js
  package-lock.json
Labels: site

#130 Update accessing-all-nested-form-controls.md
  snippets/accessing-all-nested-form-controls.md
Labels: snippet

#141 Make the builder work on windows
  builder/config.js
  builder/plugins/custom-markdown-parse.js
  package-lock.json
  package.json
Labels: site

#122 Generate stuff, add random snippet URL
  builder/helpers/index.js
  builder/layouts/random.hbs
  builder/layouts/snippet.hbs
  snippets/angular-cheat-sheet.md
  snippets/cheat-sheets-and-checklists.md
  snippets/pages/random.md
Labels: site

#155 wip: screenshot styles
  README.md
  builder/build.js
  builder/layouts/screenshot.hbs
  builder/plugins/screenshots.js
  package.json
Labels: site

#154 site updates
  README.md
  builder/layouts/index.hbs
  builder/layouts/new.hbs
  builder/layouts/readme.hbs
  builder/layouts/screenshot.hbs
  builder/layouts/slides.hbs
  builder/layouts/snippet.hbs
  builder/layouts/tag.hbs
  builder/partials/body.hbs
  builder/partials/full-body.hbs
  builder/partials/head.hbs
  builder/partials/header.hbs
  builder/partials/snippet.hbs
  builder/plugins/generate-html-files-for-screenshots.js
  builder/public/css/style.css
  builder/public/img/favicon-16x16.png
  builder/public/img/favicon-32x32.png
  builder/public/img/logo.png
  builder/public/img/logo_beta.png
Labels: site

#193 fix ng-content demo
  snippets/ng-content.md
Labels: ready for merge, snippet

#192 Sort the snippets by level starting with beginner
  .travis.yml
  builder/__tests__/README.md
  builder/__tests__/__snapshots__/index.test.js.snap
  builder/__tests__/index.test.js
  builder/helpers/index.js
  package-lock.json
  package.json
  snippets/style-bindings.md
Labels: site

#195 Move Partials Around
  builder/config.js
  builder/layouts/index.hbs
  builder/layouts/new.hbs
  builder/layouts/screenshot.hbs
  builder/layouts/slides.hbs
  builder/layouts/snippet.hbs
  builder/layouts/tag.hbs
  builder/partials/body.hbs
  builder/partials/footer.hbs
  builder/partials/full-body.hbs
  builder/partials/head.hbs
  builder/partials/header.hbs
  builder/partials/snippet.hbs
Labels: site

#200 Enables local testing
  builder/config.js
  builder/layouts/new.hbs
  builder/layouts/snippet.hbs
Labels: site

#202 docs: change title of component state debugging
  snippets/component-state-debugging.md
Labels: ready for merge

#205 Retina logo update
  builder/public/img/logo_beta.png
Labels: ready for merge, site

#203 add Staging env
  .firebaserc
  README.md
  firebase.json
  package.json
Labels: ready for merge, site

#164 Add - new snippet: Observables as outputs
  snippets/observables-as-outputs.md
Labels: snippet

#167 Add - new snippet: Preseving whitespaces
  snippets/preseving-whitespaces.md
Labels: snippet
